export const ActionTypes = {
   ADD_WATCHLIST: "ADD_WATCHLIST",
   ADD_LIKED: "ADD_LIKED",
    ADD_WATCHLATER: "ADD_WATCHLATER",
   REMOVE_WATCHLIST: "REMOVE_WATCHLIST",
 REMOVE_LIKED: "REMOVE_LIKED",
  REMOVE_WATCHLATER: "REMOVE_WATCHLATER",
  SHOW_FORM: "SHOW_FORM",
  SET_USER: "SET_USER",
  HIDE_FORM: "HIDE_FORM",
  LOG_OUT: 'LOG_OUT'
}